### ISSUE TITLE
ARM64 version and Audio only version?

### ISSUE THREAD

**Issue by tomakorea** [elonen/clapshot#56]
Hi, I'm working at home and I have a server based on Debian ARM64 (raspberry pi 5, 8gb). I tried to install Clapshot but unfortunately it seems like there is no ARM64 compiled version. Is there a way to do that ? I have all the dependencies installed and working. I think it would really benefit artists and creators that need this kind of feature without investing on a X64 CPU or expensive power electric bills.
Also, as a sound designer, I wanted to ask you if it would be possible to add an "audio only" version based on Wavesurfer for example : https://github.com/katspaugh/wavesurfer.js/  There is no alternative to mixup.audio in the open source community and I think it would be very appreciated by a lot of musicians if you could add this feature.

Thanks for your answer and your hard work

**Comment by elonen** [comment]
Hi, ARM build is actually already implemented, as I'm not developing on an M2 Macbook. I'll add a prebuilt arm64.deb in the next minor release, which I'll likely make quite soo as I'm planning to fix #55.
In the meantime, you can also build it yourself by issuing `make debian-docker` on an ARM machine, if you wish.

As for audio file upload, I'll have to think about it. There's a customization/plugin system implemented in the `dev` branch, which might be the correct place to implement it. (I've been dragging my feet with releasing that branch, however, as I feel it's somewhat over-engineered and haven't figured out how to simplify it to a proper degree.)

I'd probably implement audio files by making the ffmpeg transcoder turn them into a video so the current codebase can handle them without too much changes, which would additionally allow uploading image files. Would that work for you or does Waversurfer offer something you'd miss?

**Comment by tomakorea** [comment]
Thanks for your answer, that's awesome !

> I'd probably implement audio files by making the ffmpeg transcoder turn them into a video so the current codebase can handle them without too much changes, which would additionally allow uploading image files. Would that work for you or does Waversurfer offer something you'd miss?

I think you can definitely use your actual logic to handle audio files, the good side of wavesurfer is that the user can visualize the audio waveform and click directly on it to navigate (which is convenient), and all the process of navigation and display is handled directly by wavesurfer.
For ffmpeg, actually when sending master audio files for review, we try to stay as close as the original format as possible. For example, converting 48khz 24bits master file to 44khz 16bits creates aliasing, and lower the details. Ideally, when the user is sending a WAV file, FFmpeg could convert it to FLAC without altering bit depth or sample rate. If the user upload and mp3, then it could be used as it is.

It's just my ideas, let me know if I can help. Thank you !

**Comment by zen85** [comment]
oh i would love the ARM version. i just tried to create a docker-compose.yml and while this seems to work i fail because i am also using a rpi:
```
version: '3.8'

services:
  clapshot:
    image: elonen/clapshot:latest-demo-htadmin
    container_name: clapshot-demo
    ports:
      - "8085:80"  # Map port 8085 on the host to port 80 in the container
    volumes:
      - /dockers/clapshot/clapshotdata:/mnt/clapshot-data/data  # Map /dockers/clapshot/clapshotdata on the host to /mnt/clapshot-data/data in the container
    restart: unless-stopped

```
